### PR TITLE
Test generating CHANGELOG

### PR DESCRIPTION
**Pull request by chaspy**
ref: https://blog.yug1224.com/archives/57b7245bf95fb12307457b8c/

### CODE REVIEW

**Comment by chaspy** [comment]
This is just test `github-changes`.

We developed not based on issue, not on PR, so We should create CHANGELOG based on issues and issue's label. 🤔

**Comment by chaspy** [comment]
ref: https://github.com/github-changelog-generator/github-changelog-generator

**Comment by chaspy** [comment]
hi @kamontia 
please add v0.2.0 tag. after that, please merge.

**Comment by kamontia** [comment]
@chaspy  Thank you for your quick work!! I merge soooooon

**Pull request merged**
