### PR TITLE
Try to struct directory path

### LINKED ISSUE #134: Directory structure optimization
In the current, `main.go` is very heavy.
We should improve the directory structure.

### PR DESCRIPTION
**Pull request by kamontia**
close #134

### CODE REVIEW

**Comment by kamontia** [comment]
@chaspy It is incomplete because I can not solve the problem of self-reference well. However, the main.go file has become compact. Could you review and merge.

**Comment by chaspy** [comment]
@kamontia 
If you are NOT ready to merge this PR, please add "[REVIEW ONLY]" instead of "WIP" in the title.

**Comment by chaspy** [comment]
@kamontia 
Done my review. Please rebase and merge by yourself.

If there are problems you want to improve in the future, please create an issue.

**Comment by kamontia** [comment]
@chaspy Hi, Happy New Year:smile:

I create issue in #136.
I merge this pull request by myself.

**Pull request merged**
