### PR TITLE
Update descriptio v0.1.0

### PR DESCRIPTION
**Pull request by chaspy**
ref: https://github.com/kamontia/qs/issues/45

### CODE REVIEW

**Comment by chaspy** [comment]
@kamontia 
please review and merge

**Comment by kamontia** [comment]
Thank you for efforts. It's OK.

I want to add the demo video (gif format), Could I add this implementation on this PR???
If NOT accepted,  I create another PR.

**Comment by chaspy** [comment]
@kamontia 
please create another PR!

**Comment by kamontia** [comment]
OK

**Pull request merged**
